import os
import subprocess
import requests
from dotenv import load_dotenv
from src.models import FirmwareProject

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO = os.getenv("GITHUB_REPO")  # format: "username/repo-name"

def _run_git_command(cmd: list[str], cwd: str) -> tuple[int, str, str]:
    """Run a git command and return exit code, stdout, stderr."""
    print(f"  ▶ git {' '.join(cmd[1:])}")
    result = subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True
    )
    return result.returncode, result.stdout, result.stderr

def create_github_repo(repo_name: str, description: str = "", private: bool = True) -> dict | None:
    """Create a new GitHub repository."""
    print(f"\n📦 Creating GitHub repository: {repo_name}")
    
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    payload = {
        "name": repo_name,
        "description": description,
        "private": private,
        "auto_init": False
    }
    
    response = requests.post(
        "https://api.github.com/user/repos",
        headers=headers,
        json=payload
    )
    
    if response.status_code == 201:
        repo_data = response.json()
        print(f"  ✅ Repository created: {repo_data['html_url']}")
        return repo_data
    elif response.status_code == 422:
        # repo already exists — get it
        print(f"  ℹ️ Repository already exists, fetching details...")
        return get_github_repo(repo_name)
    else:
        print(f"  ❌ Failed to create repo: {response.json()}")
        return None

def get_github_repo(repo_name: str) -> dict | None:
    """Get an existing GitHub repository."""
    username = GITHUB_REPO.split("/")[0] if GITHUB_REPO else ""
    
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    response = requests.get(
        f"https://api.github.com/repos/{username}/{repo_name}",
        headers=headers
    )
    
    if response.status_code == 200:
        return response.json()
    return None

def init_and_push(project: FirmwareProject, project_dir: str) -> str | None:
    """Initialise git repo and push to GitHub."""
    import shutil
    print(f"\n🚀 Pushing to GitHub...")

    # remove existing .git if present to start fresh
    git_dir = os.path.join(project_dir, ".git")
    if os.path.exists(git_dir):
        shutil.rmtree(git_dir)
        print("  🗑️ Removed existing .git directory")

    github_repo = GITHUB_REPO  # use repo from .env
    
    if not github_repo:
        print("  ❌ GITHUB_REPO not set in .env")
        return None

    # get existing repo details
    repo_data = get_github_repo(github_repo.split("/")[1])
    
    if not repo_data:
        # only create if it doesn't exist
        repo_name = github_repo.split("/")[1]
        repo_data = create_github_repo(
            repo_name=repo_name,
            description=project.description,
            private=True
        )

    if not repo_data:
        print("  ❌ Could not find or create GitHub repository")
        return None

    repo_url = repo_data["clone_url"]
    auth_url = repo_url.replace(
        "https://",
        f"https://{GITHUB_TOKEN}@"
    )

    # initialise git repo
    returncode, _, stderr = _run_git_command(
        ["git", "init"], cwd=project_dir
    )
    if returncode != 0:
        print(f"  ❌ git init failed: {stderr}")
        return None

    # configure git user
    _run_git_command(
        ["git", "config", "user.email", "firmware-agent@local"],
        cwd=project_dir
    )
    _run_git_command(
        ["git", "config", "user.name", "Firmware Agent"],
        cwd=project_dir
    )

    # create .gitignore
    gitignore_content = """build/
.pio/
*.bin
*.hex
*.elf
*.map
__pycache__/
.venv/
"""
    with open(os.path.join(project_dir, ".gitignore"), "w") as f:
        f.write(gitignore_content)

    # create README
    readme_content = f"""# {project.name}

{project.description}

## Platform
- **MCU:** {project.platform.mcu if project.platform else 'Unknown'}
- **Toolchain:** {project.platform.toolchain if project.platform else 'Unknown'}
- **Version:** {project.version}

## Generated
This firmware was generated by the Firmware Agent on {project.created_at}.
"""
    with open(os.path.join(project_dir, "README.md"), "w") as f:
        f.write(readme_content)

    # create branch for this project
    branch_name = project.name.lower().replace(" ", "-")

    # stage all files
    returncode, _, stderr = _run_git_command(
        ["git", "add", "."], cwd=project_dir
    )
    if returncode != 0:
        print(f"  ❌ git add failed: {stderr}")
        return None

    # commit
    returncode, _, stderr = _run_git_command(
        ["git", "commit", "-m", f"Initial firmware: {project.name} v{project.version}"],
        cwd=project_dir
    )
    if returncode != 0:
        print(f"  ❌ git commit failed: {stderr}")
        return None

    # add remote
    _run_git_command(
        ["git", "remote", "add", "origin", auth_url],
        cwd=project_dir
    )

    # push to project-specific branch
    returncode, _, stderr = _run_git_command(
        ["git", "push", "-u", "--force", "origin", f"HEAD:{branch_name}"],
        cwd=project_dir
    )

    if returncode == 0:
        print(f"  ✅ Pushed to GitHub: {repo_data['html_url']}/tree/{branch_name}")
        project.git_repo_url = f"{repo_data['html_url']}/tree/{branch_name}"
        return project.git_repo_url
    else:
        print(f"  ❌ Push failed: {stderr}")
        return None